const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
async function harness(){
 const {cacheableURL}=await import('../source/atelier/js/offline-core.mjs');const stores=new Map(),events={},origin='https://ccatelier.top';let puts=0,failAt=Infinity,revision='old';
 const key=k=>typeof k==='string'?new URL(k,origin).href:k.url;
 const caches={async open(name){if(!stores.has(name))stores.set(name,new Map());const data=stores.get(name);return {async put(k,r){puts++;if(puts===failAt)throw Error('QuotaExceededError');data.set(key(k),r.clone());},async match(k){return data.get(key(k))?.clone();},async delete(k){return data.delete(key(k));},async keys(){return [...data.keys()].map(url=>({url}));}};},async delete(name){return stores.delete(name);},async keys(){return [...stores.keys()];}};
 const fetch=async input=>{const url=key(input);if(url.endsWith('/archive.json'))return new Response(JSON.stringify({posts:[{path:'/a/',title:'A'}]}));if(url.endsWith('/offline-shell.json'))return new Response(JSON.stringify(['/atelier/js/main.js','/atelier/css/a.css']));if(url.endsWith('/a/'))return new Response('<script src="/atelier/js/main.js"></script>');if(url.endsWith('.js'))return new Response(revision);return new Response('body{}');};
 const self={location:{origin},addEventListener:(name,fn)=>events[name]=fn,clients:{claim:async()=>{},get:async()=>({url:origin+'/a/'})},skipWaiting:async()=>{}};
 const context=vm.createContext({self,caches,fetch,URL,Response,Request,crypto,cacheableURL,console});vm.runInContext(fs.readFileSync('custom/live-sw.template','utf8').replace(/^import[^\n]+\n/,'').replaceAll('__ROOT__','"/"'),context);
 return {stores,caches,context,events,handle:data=>context.handle(data),failNext(){failAt=puts+2;},revise(){revision='new';},async request(path){let result;events.fetch({request:{url:origin+path,method:'GET',mode:'cors'},clientId:'client',respondWith:p=>result=p});return result?await result:null;}};
}
test('a failed first save leaves no snapshot, rows, or stranded assets',async()=>{const h=await harness();h.failNext();await assert.rejects(h.handle({type:'save',path:'/a/'}));const state=await h.handle({type:'list'});assert.equal(state.rows.length,0);assert.equal(state.bytes,0);});
test('failed update preserves previous article snapshot and online fetch sees new scripts',async()=>{const h=await harness();await h.handle({type:'save',path:'/a/'});const before=await h.handle({type:'list'});h.revise();h.failNext();await assert.rejects(h.handle({type:'save',path:'/a/'}));const after=await h.handle({type:'list'});assert.deepEqual(JSON.parse(JSON.stringify(after.rows)),JSON.parse(JSON.stringify(before.rows)));assert.equal(after.bytes,before.bytes);const response=await h.request('/atelier/js/main.js');assert.equal(await response.text(),'new');assert.equal(await h.request('/api/comments'),null);});
