const test=require('node:test'),assert=require('node:assert/strict');
const core=import('../source/atelier/js/performance-core.mjs'),transport=import('../source/atelier/js/performance-transport.mjs'),store=import('../source/atelier/js/performance-store.mjs');
test('original complete performance has bounded score, authored light and shot tracks',async()=>{const {originalPerformance,validatePerformance}=await core,p=originalPerformance();assert.equal(p.beats,64);assert.equal(p.notes.length,268);assert.equal(p.shots.length,5);assert.deepEqual(validatePerformance(p),p);p.notes[0].velocity=0;assert.notDeepEqual(p,originalPerformance());});
test('evaluateAt is direct-seek deterministic and smoothly interpolates shared render state',async()=>{const {originalPerformance,evaluateAt}=await core,p=originalPerformance();const expected=evaluateAt(p,25);for(let beat=0;beat<25;beat+=.13)evaluateAt(p,beat);assert.deepEqual(evaluateAt(p,25),expected);assert.equal(expected.shot.scale,1.07);assert.deepEqual(evaluateAt(p,24,{motion:false}).shot,{name:'kit',scale:1.09,x:0,y:-2});assert.equal(evaluateAt(p,-100).beat,0);assert.equal(evaluateAt(p,Infinity).beat,64);assert.equal(evaluateAt(p,0).strikes.kick.elapsed,0);assert.equal(evaluateAt(p,64).strikes.kick.elapsed,4*60000/112);});
test('drum editing cycles strong soft rest and cue edits are canonical without touching source',async()=>{const {originalPerformance,setDrum,setCue}=await core,p=originalPerformance();let next=setDrum(p,8,'tom',0);assert.equal(next.notes.find(n=>n.instrument==='tom'&&n.beat===32).velocity,1);next=setDrum(next,8,'tom',0);assert.equal(next.notes.find(n=>n.instrument==='tom'&&n.beat===32).velocity,.5);next=setDrum(next,8,'tom',0);assert.ok(!next.notes.find(n=>n.instrument==='tom'&&n.beat===32));next=setCue(next,'shots',8,{shot:'kit'});assert.deepEqual(next.shots.find(c=>c.beat===32),{beat:32,shot:'kit'});assert.ok(!p.shots.find(c=>c.beat===32));assert.throws(()=>setDrum(p,64,'tom',0));assert.throws(()=>setCue(p,'shots',0,{shot:'unknown'}));});
test('validator rejects extra fields, sparse/accessor data, duplicate cues, nonfinite and oversized projects',async()=>{const {originalPerformance,validatePerformance}=await core;for(const mutate of [p=>p.extra=1,p=>p.beats=10000,p=>p.bpm=Infinity,p=>p.title='bad\nname',p=>p.notes.push({...p.notes[0]}),p=>p.lights.shift(),p=>p.shots.push({...p.shots[0]}),p=>p.notes[0].beat=.1,p=>p.notes[0].velocity=2,p=>delete p.notes[0],p=>Object.defineProperty(p.notes[0],'beat',{get(){throw Error('getter must not execute');}})]){const p=originalPerformance();mutate(p);assert.throws(()=>validatePerformance(p));}});
test('project save/reload includes all tracks, uses its own key and leaves recording slots intact',async()=>{const {originalPerformance,setCue,evaluateAt}=await core,{savePerformance,loadPerformance,PERFORMANCE_KEY}=await store;const data=new Map([['cc-live-take-v1:old','keep'],['unrelated-key','keep too']]),storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)};const p=setCue(originalPerformance(),'lights',8,{color:'rose',level:.6});savePerformance(storage,p);assert.deepEqual(evaluateAt(loadPerformance(storage),33),evaluateAt(p,33));assert.equal(data.get('cc-live-take-v1:old'),'keep');assert.equal(data.get('unrelated-key'),'keep too');assert.ok(data.has(PERFORMANCE_KEY));assert.throws(()=>savePerformance({setItem(){throw Error('quota');}},p));data.set(PERFORMANCE_KEY,'{}');assert.throws(()=>loadPerformance(storage));});
test('file parser is strict and bounded without performing an upload',async()=>{const {parsePerformance}=await store;assert.throws(()=>parsePerformance(' '.repeat(500001)));assert.throws(()=>parsePerformance('{bad'));assert.throws(()=>parsePerformance('{}'));});
test('transport preserves position through pause resume and switches clocks without replay burst',async()=>{const {originalPerformance}=await core,{PerformanceTransport}=await transport;let now=0,audioNow=100,cancelled=0;const hits=[],p=originalPerformance(),t=new PerformanceTransport(p,{now:()=>now,schedule:(n,d)=>hits.push([n.beat,d]),cancel:()=>cancelled++});t.play();t.tick();assert.ok(hits.length);now=2;t.tick();t.pause();const held=t.position;now=12;assert.equal(t.position,held);t.clock(()=>audioNow);assert.equal(t.position,held);t.play();audioNow+=.5;assert.ok(t.position>held);const before=hits.length;t.seek(32);t.tick();assert.ok(hits.slice(before).every(([b])=>b>=32));assert.ok(cancelled>=5);t.stop();assert.equal(t.position,0);});
test('end seek, stalled scheduler and replacement never emit missed historical attacks',async()=>{const {originalPerformance}=await core,{PerformanceTransport}=await transport;let now=0;const hits=[],p=originalPerformance(),t=new PerformanceTransport(p,{now:()=>now,schedule:n=>hits.push(n.beat)});t.play();now=10;t.tick();assert.ok(hits.every(b=>b>=18));t.seek(64);t.tick();assert.equal(t.state,'ended');t.play();assert.equal(t.position,0);t.replace({...p,beats:32,notes:p.notes.filter(n=>n.beat<32)});assert.equal(t.state,'paused');assert.equal(t.project.beats,32);});

test('cue enum values cannot be coerced from arrays, null or objects',async()=>{const {originalPerformance,validatePerformance}=await core;for(const [track,key,label] of [['lights','color','blue'],['shots','shot','wide']])for(const value of [[label],null,{},new String(label)]){const p=originalPerformance();p[track][0][key]=value;assert.throws(()=>validatePerformance(p));}});
test('in-flight text import cannot overwrite a later edit, undo/load intention or newer import',async()=>{
 const {PerformanceImport}=await store,{originalPerformance,setDrum}=await core,gate=new PerformanceImport();let resolve;let project=originalPerformance();const old=gate.read(()=>new Promise(r=>resolve=r));gate.invalidate();project=setDrum(project,0,'kick',0);const edited=structuredClone(project);resolve(JSON.stringify(originalPerformance()));assert.equal(await old,null);assert.deepEqual(project,edited);
 let release;const first=gate.read(()=>new Promise(r=>release=r));const newer=await gate.read(()=>Promise.resolve(JSON.stringify(edited)));release(JSON.stringify(originalPerformance()));assert.equal(await first,null);assert.deepEqual(newer,edited);
 let reject;const staleFailure=gate.read(()=>new Promise((_r,j)=>reject=j));gate.invalidate();reject(Error('old failure'));assert.equal(await staleFailure,null);await assert.rejects(gate.read(()=>Promise.resolve('{}')));
});
