import {initDialogs, initSettings} from './ui.js';
import {initCover} from './cover.js';
import {initSearch} from './search.js';
import {initEffects} from './effects.js';
import {initRhythm} from './rhythm.js';
import {initReading} from './reading.js';
import {initBackstage} from './backstage.js';
import {initCommunity, initModeration} from './community.js';
import {initAfterHours} from './after-hours.js';
import {initArchive} from './archive.js';
import {initQueue} from './queue.js';
import {initReader} from './reader.js';
import {initNotebook} from './notebook.js';
import {initCodeStudio} from './code-studio.js';
import {initOffline} from './offline.js';
import {initStudio} from './studio.js';
import {initStageEngine} from './stage-engine.js';

initSettings();
initDialogs();
initCover();
initSearch();
initEffects();
initRhythm();
initReading();
initBackstage();
initCommunity();
initModeration();
initAfterHours();
initQueue();
initArchive();
initReader();
initNotebook();
initCodeStudio();
initOffline();
initStudio();
initStageEngine();
